name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: cmake configure
      run: mkdir build && cmake -B ${{github.workspace}}/build 
    - name: make
      run: cd ${{github.workspace}}/build && make main
    - name: make python module
      run: cd ${{github.workspace}}/build && make bbgym
    - name: run simple instance
      run: cd ${{github.workspace}}/build && ./main < ../case/1.txt
    - name: run cbfs instance
      run: cat ${{github.workspace}}/case/5.txt | python -c "import os; import sys; work_dir=os.environ.get('github.workspace'); sys.path.append(work_dir + "/build/"); import bbgym; bbgym.solve_cbfs();"
    - name: run bfs instance
      run: cat ${{github.workspace}}/case/5.txt | python -c "import os; import sys; work_dir=os.environ.get('github.workspace'); sys.path.append(work_dir + "/build/"); import bbgym; bbgym.solve_bfs();"